### PR TITLE
[DOC-2799] Add SDK API documentation

### PR DESCRIPTION
**Pull request by BlackstoneEngineering**
This PR is to add doxygen style comments to the functions for public documentation. 

Doxygen will be used to generate XML. 
Doxybook2 will be used to generate XML to markdown. 

This markdown file will then be the API reference used for hosting publically.

### CODE REVIEW

**Comment by BlackstoneEngineering** [comment]
Initial commit made so docs team can copy-edit. 

Not finished yet, do not merge.

**Comment by DEskinazi** [comment]
Reviewed and approved for publishing by Docs Team.

**Comment by BlackstoneEngineering** [comment]
@tung-vu-td - ready to merge. Please review / merge at your convenience.

**Review by tung-vu-td — APPROVED** [review]
LGTM

**Pull request merged**
